### ISSUE TITLE
Allow for inline editor instead of replace field

### ISSUE THREAD

**Issue by eikishi01** [jziggas/ng-ck#5]
Allow to call CKEditor.inline() instead of CKEditor.replace() with an attribute perhaps?

**Comment by jziggas** [comment]
That is not possible with a component so it would require either rewriting everything as an attribute directive or perhaps keeping the current component and adding a new attribute directive for inline editors. If this is something you're willing to make a pull request for I think adding a new attribute directive specifically for this case would be interesting.
